/*
app_events.h
*/

#ifndef _APP_EVENTS_H_
#define _APP_EVENTS_H_


// #include "esp_check.h"
// #include "esp_event.h"
// #include "esp_event_base.h"


#ifdef __cplusplus
extern "C" {
#endif



//------------------------------------------------------------------------------
// APP_TOUCH_EVENTS
//------------------------------------------------------------------------------
ESP_EVENT_DECLARE_BASE(APP_TOUCH_EVENTS);

enum {
    // Events generated by and sent from the "Touch Pads" module.
    APP_TOUCH_VALUE_CHANGE_EVENT,

    // Events to be sent to the "Touch Pads" module.
    APP_TOUCH_FORCE_UPDATE  //TODO: needs to be implemented.
};

typedef struct {
    time_t utc_timestamp;
    uint32_t touch_value;
    uint8_t touch_pad_num;
} app_touch_value_change_event_payload;



//------------------------------------------------------------------------------
// ???
//------------------------------------------------------------------------------



#ifdef __cplusplus
}
#endif


#endif // _APP_EVENTS_H_
